#################################################
#
# Source original: https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
# Modified with existing scripts on ./nginx folder for nginx_nextcloud_network
#
##################################################

version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      default:

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB
    volumes:
      - wordpress:/var/www/html
    networks:
      default:

  webserver:
    depends_on:
      - wordpress
    image: nginx
    container_name: webserver
    networks:
      default:
    ports:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST,www.$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$VIRTUAL_HOST,www.$VIRTUAL_HOST
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  wordpress:
  dbdata:

networks:
  default:
    external:
      name: nginx_nextcloud_network
