#==============  secrets ======================================
#
#     POC: to understand the use of docker-compose secrets
#
#===============================================================
# file to create NextCloud using MariaDB and ngInx
version: '3.2' 

services:
  proxy:
  #  original image from internet documents, uncomment to create a new docker container
  #  image: jwilder/nginx-proxy:alpine
  # image modified to allow upload big files
  #  image: nextcloud-proxy
  # find following image on AWS->ECR>Repositories > nextcloud
  # you have to login first before pull the image see pushCommandsFromAWS.md
    image: 690049365056.dkr.ecr.us-east-1.amazonaws.com/nextcloud:nextcloud-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /nextcloud/mydeskweb.com/proxy/conf.d:/etc/nginx/conf.d:rw
      - /nextcloud/mydeskweb.com/vhost.d:/etc/nginx/vhost.d:rw
      - /nextcloud/mydeskweb.com/proxy/html:/usr/share/nginx/html:rw
      - /nextcloud/mydeskweb.com/proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - /nextcloud/mydeskweb.com/proxy/certs:/etc/nginx/certs:rw
      - /nextcloud/mydeskweb.com/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /nextcloud/mydeskweb.com/proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: mariadb-mydeskweb.com
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=CapitanAmerica#2020
      - MYSQL_HOST=db
        #actually secrets is only supported for MYSQL_PASSWORD, MYSQL_DATABASE, MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_mysql_password
      - MYSQL_DATABASE_FILE=/run/secrets/secret_mysql_database
      - MYSQL_USER_FILE=/run/secrets/secret_mysql_user
    restart: unless-stopped
    secrets:
      - secret_mysql_password
      - secret_mysql_database
      - secret_mysql_user
  
  mydeskweb:
    image: nextcloud:latest
    container_name: nextcloud-mydeskweb.com
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    expose:
      - 80
      - 443
    volumes:
      - /nextcloud/mydeskweb.com/html:/var/www/html
      - /nextcloud/mydeskweb.com/config:/var/www/html/config
      - /nextcloud/mydeskweb.com/custom_apps:/var/www/html/custom_apps
      - /nextcloud/mydeskweb.com/data:/var/www/html/data
      - /nextcloud/mydeskweb.com/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/secret_nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/secret_nextcloud_admin_password
      - MYSQL_DATABASE_FILE=/run/secrets/secret_mysql_database
      - MYSQL_USER_FILE=/run/secrets/secret_mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_mysql_password
      # =========== proxy and lentsencryp variables ================
      - VIRTUAL_HOST=mydeskweb.com
      - LETSENCRYPT_HOST=mydeskweb.com
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
    restart: unless-stopped
    secrets:
      - secret_nextcloud_admin_user
      - secret_nextcloud_admin_password
      - secret_mysql_database
      - secret_mysql_user
      - secret_mysql_password
  questinnovations:
    image: nginx
    container_name: questinnovations.net
    networks:
      - nextcloud_network
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=questinnovations.net
      - LETSENCRYPT_HOST=questinnovations.net
      - LETSENCRYPT_EMAIL=pablo.trujillo.tapia@hotmail.com
    volumes:
        - /nextcloud/www/questinnovations.net:/usr/share/nginx/html:ro
    depends_on:
      - letsencrypt
      - proxy
    restart: unless-stopped

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
    #      - "/folder_on_disk/data:/home/username/"
      - /nextcloud/www/questinnovations.net:/home/ftpusers/ptrujillo
      - /nextcloud/www/paveltrujillo.info:/home/ftpusers/pavelt
      - /nextcloud/www/paveltrujillo.info:/home/ftpusers/bob
      - "/etc/ssl/private/:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
      - "/etc/ssl/private:/etc/ssl/private/"
    environment:
      PUBLICHOST: "mydeskweb.com"
      FTP_USER_NAME: pavelt
      FTP_USER_PASS: batlink1977
      FTP_USER_HOME: /home/pavelt
      PURE_PASSWDFILE: /etc/pure-ftpd/passwd/pureftpd.passwd
# also for ssl/tls:
      ADDED_FLAGS: "--tls=2"
      TLS_USE_DSAPRAM: "true"
    restart: always
    networks:
      nextcloud_network:


volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:

secrets:
  secret_mysql_password:
    file: ./secrets/secret_mysql_password.txt
  secret_mysql_database:
    file: ./secrets/secret_mysql_database.txt
  secret_mysql_user:
    file: ./secrets/secret_mysql_user.txt
  secret_nextcloud_admin_user:
    file: ./secrets/secret_nextcloud_admin_user.txt
  secret_nextcloud_admin_password:
    file: ./secrets/secret_nextcloud_admin_password.txt