#================================================================
# file to create NextCloud using MariaDB and ngInx
#================================================================

version: '3.2'

services:

  nextcloud:
    image: nextcloud:latest
    container_name: ${NEXTCLOUD_SERVICE}
    networks: 
      default:
    external_links: 
      - nginx-proxy
      - letsencrypt
    depends_on:
      #- letsencrypt-proxy-companion
      #- nginx-proxy
      - mariadb
    volumes:
      # use COMPOSE_PROJECT_NAME instead of nextcloud hard name
      - nextcloud:/var/www/html
      # use html path instead of nextcloud volume as the original doc for backup purposes and restore purposes
      - ${NEXTCLOUD_HTTP_ROOT}/config:/var/www/html/config
      - ${NEXTCLOUD_HTTP_ROOT}/custom_apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_HTTP_ROOT}/data:/var/www/html/data
      - ${NEXTCLOUD_HTTP_ROOT}/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_HOST=${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: ${DATABASE_SERVICE}
    networks:
      default:
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped

volumes:
  nextcloud:
  mariadb:

networks: 
  default:
    external:
      name: nginx_nextcloud_network
