#================================================================
# file to create NextCloud using MariaDB and ngInx
#================================================================
# version used for docker-compose version 1.23.2, build 1110ad01
# version: '4.2' 
services:
  nextcloud:
    image: myowncloud
    build: ../nextCloudImage
    container_name: ${NEXTCLOUD_SERVICE}
    networks: 
      default:
    # external_links: 
    #   - nginx-proxy
    #   - letsencrypt 
    depends_on:
      #- letsencrypt-proxy-companion
      #- nginx-proxy
      - mariadb
      # - redis
      # - cron
    volumes:
      # use COMPOSE_PROJECT_NAME instead of nextcloud hard name
      - nextcloud:/var/www/html
      # use html path instead of nextcloud volume as the original doc for backup purposes and restore purposes
      - ${NEXTCLOUD_HTTP_ROOT}/config:/var/www/html/config
      - ${NEXTCLOUD_HTTP_ROOT}/custom_apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_HTTP_ROOT}/data:/var/www/html/data
      - ${NEXTCLOUD_HTTP_ROOT}/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=${NEXTCLOUD_SERVICE},www.${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_HOST=${NEXTCLOUD_SERVICE},www.${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
      - REDIST_HOST=mydeskweb.redis
      - REDIS_HOST_PORT=6379   # default 6379
      - 'REDIS_HOST_PASSWORD=nextcloud_redis_pass'
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    container_name: ${DATABASE_SERVICE}
    networks:
      default:
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped

  redis:
    image: redis
    container_name: mydeskweb.redis
    restart: unless-stopped
    command: redis-server --requirepass nextcloud_redis_pass
    expose: 
      - 6379
    networks:
      - default
    #  docker run --name mydeskweb-redis -d redis redis-server --save 60 1 --loglevel warning

  cron:
    # https://help.nextcloud.com/t/nextcloud-docker-setup-help-needed-with-cron/188907
    image: nextcloud
    container_name: mydeskweb.cron
    volumes:
      - ${NEXTCLOUD_HTTP_ROOT}:/var/www/html
      - ${NEXTCLOUD_HTTP_ROOT}/config:/var/www/html/config
      - ${NEXTCLOUD_HTTP_ROOT}/data:/var/www/html/data
    entrypoint: /cron.sh
    restart: unless-stopped
    networks:
      default:

volumes:
  nextcloud:
  mariadb:

networks: 
  default:
    name: mydeskweb_nextcloud_network
    external: true
