#===========================================================#
# Pablo Trujillo                          02/01/2022        # 
#                                                           #
# Creates a new container for nginx web site                #
# Define CONTAINER_NAME either as an encironment cariable   #
# e.g. export CONTAINER_NAME=paveltrujillo.local            #
# Or using the command:                                     #
# CONTAINER_NAME=paveltrujillo.local docker-compose up -d   #
#===========================================================#
version: '3.2' 

services:

  nginx:
    image: nginx
    container_name: ${CONTAINER_NAME}
    networks: 
      default:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=${CONTAINER_NAME},www.${CONTAINER_NAME}
      - LETSENCRYPT_HOST=${CONTAINER_NAME},www.${CONTAINER_NAME}
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - LETSENCRYPT_EMAIL="pablitott@gmail.com"
    volumes:
        - /nextcloud/www/${CONTAINER_NAME}:/usr/share/nginx/html:ro
        - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   - letsencrypt
    #   - proxy
    restart: unless-stopped

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
       default:
    volumes:
      - /nextcloud/www/${CONTAINER_NAME}:/home/ftpusers/pavelt
      - /nextcloud/ftpd/pwd:/etc/pure-ftpd/passwd
      #- /nextcloud/www/paveltrujillo.info:/home/
      #- "/etc/ssl/private/:/etc/pure-ftpd/passwd"
      # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
      - "/nextcloud/ftpd/certs:/etc/ssl/private/"
    environment:
      PUBLICHOST: ${CONTAINER_NAME}
      FTP_USER_NAME: pavelt
      FTP_USER_PASS: batlink1977
      FTP_USER_HOME: /home/ftpusers/pavelt
      PURE_PASSWDFILE: /etc/pure-ftpd/passwd/pureftpd.passwd
      # also for ssl/tls:
      ADDED_FLAGS: "--tls=1"
      #TLS_USE_DSAPRAM: "true"
    restart: always
networks:
  default:
    external:
      name: nginx_nextcloud_network

## errors trying to up because port 21 was in use, resolved as
# who is using port 21
# sudo netstat -nlpt |grep 21
# kill port 21 user
# sudo kill `sudo lsof -t -i:3306`
# CONTAINER_NAME=drawingmonos.com docker-compose up -d