FROM nextcloud:latest 
#29.0.1
RUN apt update & apt-get upgrade
RUN apt-get install apt-utils -y
RUN apt-get install libmagickcore-6.q16-6-extra -y
# RUN apt-get install php-imagick 
RUN apt-get install smbclient -y
