FROM nextcloud:27.1.10
# RUN apt-get update && apt-get upgrade -y 
# RUN apt-get install apt-utils -y
RUN apt-get install libmagickcore-6.q16-6-extra -y
# RUN apt-get install php-imagick 
# RUN apt-get install imagemagick -y
