#################################################
# Original script, not working on local machine
# Source: https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
#
##################################################
version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: wordpress.local.env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: wordpress.local.env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    networks:
      - app-network
    ports:
      - 80
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot_etc:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email pablitott@gmail.com --agree-tos --no-eff-email --staging -d absolutehandymanservices.com -d www.absolutehandymanservices.com

volumes:
  certbot_etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge