version: '3.2'

services:

  questinnovations:
    image: nginx
    container_name: questinnovations.local
    networks: 
      default:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=questinnovations.local
      - LETSENCRYPT_HOST=questinnovations.local
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
    volumes:
      - /nextcloud/www/questinnovations.local:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
#    depends_on:
    #   - proxy
    #   - letsencrypt
    restart: unless-stopped

networks: 
  default:
    external:
      name: nginx_nextcloud_network
