#================================================================
# file to create NextCloud using MariaDB and ngInx
#================================================================

version: '3.2'

services:

  nextcloud:
    image: nextcloud:latest
    container_name: ${NEXTCLOUD_SERVICE}
    networks: 
      default:
    depends_on:
      #- letsencrypt
      #- proxy
      - mariadb
    volumes:
      # use html path instead of nextcloud volume as the original doc for backup purposes
      - nextcloud:/var/www/html
      - /nextcloud/${NEXTCLOUD_SERVICE}/config:/var/www/html/config
      - /nextcloud/${NEXTCLOUD_SERVICE}/custom_apps:/var/www/html/custom_apps
      - /nextcloud/${NEXTCLOUD_SERVICE}/data:/var/www/html/data
      - /nextcloud/${NEXTCLOUD_SERVICE}/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=${NEXTCLOUD_SERVICE},www.${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_HOST=${NEXTCLOUD_SERVICE},www.${NEXTCLOUD_SERVICE}
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: ${DATABASE_SERVICE}
    networks:
      default:
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped

volumes:
  nextcloud:
  mariadb:

networks: 
  default:
    external:
      name: nginx_nextcloud_network
