#============================================================
# TODO: create a dev barnch and make adjustments there
#
#============================================================
version: '3.2' 

services:

  paveltrujillo:
    image: nginx
    container_name: paveltrujillo
    networks: 
      default:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=paveltrujillo.info,www.paveltrujillo.info
      - LETSENCRYPT_HOST=paveltrujillo.info,www.paveltrujillo.info
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
    volumes:
        - /nextcloud/www/paveltrujillo.info:/usr/share/nginx/html:ro
        - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   - letsencrypt
    #   - proxy
    restart: unless-stopped
networks: 
  default:
    external:
      name: nginx_nextcloud_network
