#============================================================
# TODO: create a dev barnch and make adjustments there
#
#============================================================
version: '3.2' 

services:

  nginx:
    image: nginx
    container_name: ${CONTAINER_NAME}
    networks: 
      default:
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=pablitott@gmail.com
    volumes:
        - /nextcloud/www/${CONTAINER_NAME}:/usr/share/nginx/html:ro
        - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   - letsencrypt
    #   - proxy
    restart: unless-stopped

networks: 
  default:
    external:
      name: nginx_nextcloud_network
